import { Category, Product, StoreSettings, Order } from '../types';

export const initialSettings: StoreSettings = {
  brand_name: "Aleez Perfumes",
  tagline: "Discover Your Signature Scent",
  description: "Haute perfumery and artisanal essences. Handcrafted fragrances designed for elegance and distinction.",
  phone: "+91 9345526905",
  whatsapp: "+919345526905",
  email: "aleez.perfumes818@gmail.com",
  instagram: "@aleez.parfums",
  instagram_url: "https://instagram.com/aleez.parfums",
  currency: "INR",
  currency_symbol: "₹",
  free_shipping_threshold: 999,
  standard_shipping_fee: 99,
  announcement_bar: "Complimentary luxury express shipping across India on orders above ₹999",
  is_store_open: true,
};

export const initialCategories: Category[] = [
  {
    id: "cat-1",
    name: "Eau de Parfum",
    slug: "eau-de-parfum",
    description: "Exquisite concentrated spray fragrances with exceptional longevity and projection.",
    image_url: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=80",
    display_order: 1,
    is_active: true,
  },
  {
    id: "cat-2",
    name: "Artisanal Attars",
    slug: "artisanal-attars",
    description: "Non-alcoholic concentrated botanical and amber oils blended to absolute perfection.",
    image_url: "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?auto=format&fit=crop&w=800&q=80",
    display_order: 2,
    is_active: true,
  },
  {
    id: "cat-3",
    name: "Pure Oud Collection",
    slug: "pure-oud-collection",
    description: "Rare and authentic wild agarwood distillations aged for unmatched depth and majesty.",
    image_url: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=80",
    display_order: 3,
    is_active: true,
  },
  {
    id: "cat-4",
    name: "Oriental & Woody",
    slug: "oriental-woody",
    description: "Warm, magnetic compositions of aged sandalwood, rich spices, and golden resinous ambers.",
    image_url: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=800&q=80",
    display_order: 4,
    is_active: true,
  },
  {
    id: "cat-5",
    name: "Floral & Fresh",
    slug: "floral-fresh",
    description: "Invigorating Mediterranean citrus notes, ethereal white florals, and clean crisp musks.",
    image_url: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80",
    display_order: 5,
    is_active: true,
  },
  {
    id: "cat-6",
    name: "Luxury Gift Sets",
    slug: "luxury-gift-sets",
    description: "Bespoke gift boxes encased in velvet packaging, crafted for the true fragrance aficionado.",
    image_url: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=800&q=80",
    display_order: 6,
    is_active: true,
  },
];

export const initialProducts: Product[] = [
  {
    id: "prod-1",
    name: "Royal Amber Royale",
    slug: "royal-amber-royale",
    category_id: "cat-4",
    category_name: "Oriental & Woody",
    price: 2499,
    sale_price: 1999,
    description: "Royal Amber Royale is an opulent coronation of warm, resinous golden amber and Calabrian bergamot. Layered with velvety vanilla, tonka bean, and creamy Mysore sandalwood, it commands presence wherever you walk.",
    fragrance_family: "Oriental Amber Woody",
    top_notes: "Calabrian Bergamot, Pink Peppercorn, Cardamom Pods",
    heart_notes: "Golden Amber Resin, Bulgarian Damask Rose, Indonesian Patchouli",
    base_notes: "Madagascar Vanilla, Creamy Mysore Sandalwood, Roasted Tonka Bean",
    volume_ml: 50,
    stock_quantity: 35,
    sku: "ALZ-RAR-050",
    is_bestseller: true,
    is_new_arrival: false,
    is_featured: true,
    is_active: true,
    rating: 4.9,
    review_count: 54,
    images: [
      {
        id: "img-1-1",
        image_url: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1000&q=80",
        alt_text: "Royal Amber Royale - Front view with gold engraved cap",
        display_order: 1,
        is_primary: true,
      },
      {
        id: "img-1-2",
        image_url: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=1000&q=80",
        alt_text: "Royal Amber Royale - Luxury unboxing and packaging",
        display_order: 2,
        is_primary: false,
      },
    ],
  },
  {
    id: "prod-2",
    name: "Velvet Oud Noir",
    slug: "velvet-oud-noir",
    category_id: "cat-3",
    category_name: "Pure Oud Collection",
    price: 3299,
    sale_price: 2799,
    description: "An intoxicating blend of wild Cambodian agarwood and smoky leather, wrapped in mysterious dark Damask rose. Velvet Oud Noir radiates nocturnal power and opulent luxury.",
    fragrance_family: "Dark Woody Oud",
    top_notes: "Kashmiri Saffron, Smoked Cinnamon Bark, Nutmeg",
    heart_notes: "Damask Rose, Frankincense, Atlas Cedar",
    base_notes: "Cambodian Agarwood (Oud), Tuscan Leather, Warm Ambergris",
    volume_ml: 50,
    stock_quantity: 20,
    sku: "ALZ-VON-050",
    is_bestseller: true,
    is_new_arrival: true,
    is_featured: true,
    is_active: true,
    rating: 5.0,
    review_count: 68,
    images: [
      {
        id: "img-2-1",
        image_url: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1000&q=80",
        alt_text: "Velvet Oud Noir - Dark flacon with warm gold detailing",
        display_order: 1,
        is_primary: true,
      },
      {
        id: "img-2-2",
        image_url: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1000&q=80",
        alt_text: "Velvet Oud Noir - Side profile",
        display_order: 2,
        is_primary: false,
      },
    ],
  },
  {
    id: "prod-3",
    name: "Santal Imperial",
    slug: "santal-imperial",
    category_id: "cat-4",
    category_name: "Oriental & Woody",
    price: 2699,
    sale_price: 2199,
    description: "A tranquil masterpiece centered on sustainably harvested sandalwood, laced with soothing green cardamom, powdered iris, and subtle whispers of cedar.",
    fragrance_family: "Woody Floral Musk",
    top_notes: "Green Cardamom, Violet Leaves, Egyptian Papyrus",
    heart_notes: "Florentine Iris, White Cedarwood, Amber",
    base_notes: "Mysore Sandalwood, Cashmere Wood, Silken White Musk",
    volume_ml: 50,
    stock_quantity: 28,
    sku: "ALZ-SIM-050",
    is_bestseller: false,
    is_new_arrival: true,
    is_featured: true,
    is_active: true,
    rating: 4.8,
    review_count: 36,
    images: [
      {
        id: "img-3-1",
        image_url: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=1000&q=80",
        alt_text: "Santal Imperial bottle with golden accents",
        display_order: 1,
        is_primary: true,
      },
    ],
  },
  {
    id: "prod-4",
    name: "Elysian Rose Attar",
    slug: "elysian-rose-attar",
    category_id: "cat-2",
    category_name: "Artisanal Attars",
    price: 1499,
    sale_price: 1199,
    description: "Pure concentrated botanical perfumed oil distilled from freshly handpicked Taif roses blended into an aged sandalwood base. 100% alcohol-free with 24-hour lasting potency.",
    fragrance_family: "Pure Floral Oil",
    top_notes: "Taif Rose Petals, Dewy Morning Greens",
    heart_notes: "Damascena Absolute, Geranium Bourbon",
    base_notes: "White Amber Oil, Aged Sandalwood Foundation",
    volume_ml: 12,
    stock_quantity: 42,
    sku: "ALZ-ERA-012",
    is_bestseller: true,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    rating: 4.9,
    review_count: 73,
    images: [
      {
        id: "img-4-1",
        image_url: "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?auto=format&fit=crop&w=1000&q=80",
        alt_text: "Elysian Rose Attar artisanal crystal bottle",
        display_order: 1,
        is_primary: true,
      },
    ],
  },
  {
    id: "prod-5",
    name: "Midnight Saffron",
    slug: "midnight-saffron",
    category_id: "cat-1",
    category_name: "Eau de Parfum",
    price: 2899,
    sale_price: 2399,
    description: "The golden spice of Kashmir saffron collides with spicy black pepper, sweet tobacco flower, and smoked bourbon vanilla. A magnetic evening fragrance designed to turn heads.",
    fragrance_family: "Spicy Gourmand Leather",
    top_notes: "Kashmiri Saffron, Black Pepper, Coriander Seed",
    heart_notes: "Tobacco Blossom, Cocoa Butter, Dried Royal Plum",
    base_notes: "Bourbon Vanilla, Smooth Leather, Guaiac Wood",
    volume_ml: 50,
    stock_quantity: 16,
    sku: "ALZ-MDS-050",
    is_bestseller: false,
    is_new_arrival: true,
    is_featured: true,
    is_active: true,
    rating: 4.7,
    review_count: 29,
    images: [
      {
        id: "img-5-1",
        image_url: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&w=1000&q=80",
        alt_text: "Midnight Saffron Eau de Parfum",
        display_order: 1,
        is_primary: true,
      },
    ],
  },
  {
    id: "prod-6",
    name: "Aqua Celestia",
    slug: "aqua-celestia",
    category_id: "cat-5",
    category_name: "Floral & Fresh",
    price: 1999,
    sale_price: 1699,
    description: "A crisp, exhilarating Mediterranean sea breeze captured in crystal glass. Bright Sicilian lime, sparkling sea salt, and refreshing mint flow into sun-drenched neroli and mineral driftwood.",
    fragrance_family: "Aquatic Citrus Floral",
    top_notes: "Sicilian Lime, Sea Salt Crystals, Crushed Mint",
    heart_notes: "Tunisian Neroli, Hedione Jasmine, Petitgrain",
    base_notes: "Mineral Driftwood, Clean White Musk, Haitian Vetiver",
    volume_ml: 50,
    stock_quantity: 48,
    sku: "ALZ-AQC-050",
    is_bestseller: false,
    is_new_arrival: false,
    is_featured: false,
    is_active: true,
    rating: 4.8,
    review_count: 24,
    images: [
      {
        id: "img-6-1",
        image_url: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=1000&q=80",
        alt_text: "Aqua Celestia Fresh Fragrance",
        display_order: 1,
        is_primary: true,
      },
    ],
  },
];

export const initialOrders: Order[] = [
  {
    id: "ord-101",
    order_number: "ALZ-892401-419",
    customer_name: "Farhan Malik",
    customer_email: "farhan.malik@example.com",
    customer_phone: "+91 9876543210",
    shipping_address: "Flat 402, Royal Palms, Banjara Hills",
    shipping_city: "Hyderabad",
    shipping_state: "Telangana",
    shipping_pincode: "500034",
    subtotal: 4798,
    shipping_charge: 0,
    total_amount: 4798,
    payment_method: "razorpay",
    payment_status: "paid",
    order_status: "processing",
    razorpay_order_id: "order_Kj92n84aLm89Qx",
    razorpay_payment_id: "pay_Kj93x97sTy12Lk",
    items: [
      {
        product_id: "prod-1",
        product_name: "Royal Amber Royale",
        product_image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=400&q=80",
        unit_price: 1999,
        quantity: 1,
        total_price: 1999,
      },
      {
        product_id: "prod-2",
        product_name: "Velvet Oud Noir",
        product_image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=400&q=80",
        unit_price: 2799,
        quantity: 1,
        total_price: 2799,
      },
    ],
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: "ord-102",
    order_number: "ALZ-781932-512",
    customer_name: "Ayesha Siddiqui",
    customer_email: "ayesha.s@example.com",
    customer_phone: "+91 9811223344",
    shipping_address: "12B, Rose Villa, Indiranagar",
    shipping_city: "Bengaluru",
    shipping_state: "Karnataka",
    shipping_pincode: "560038",
    subtotal: 1199,
    shipping_charge: 0,
    total_amount: 1199,
    payment_method: "razorpay",
    payment_status: "paid",
    order_status: "delivered",
    razorpay_order_id: "order_Lm11s32bKq44Zx",
    razorpay_payment_id: "pay_Lm12p88dRt99Wq",
    items: [
      {
        product_id: "prod-4",
        product_name: "Elysian Rose Attar",
        product_image: "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?auto=format&fit=crop&w=400&q=80",
        unit_price: 1199,
        quantity: 1,
        total_price: 1199,
      },
    ],
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];
